version: 2
jobs:
    build:
        docker:
            - image: circleci/python:2.7
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: source .circleci/install-deps.sh
            - run:
                name: Run tests
                command: source .circleci/run-tests.sh
    build:
        docker:
            - image: circleci/python:3.6
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: source .circleci/install-deps.sh
            - run:
                name: Run tests
                command: source .circleci/run-tests.sh
    build:
        docker:
            - image: circleci/python:latest
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: source .circleci/install-deps.sh
            - run:
                name: Run tests
                command: source .circleci/run-tests.sh
